---
# dataverse/tasks/dataverse-prereqs.yml

- name: Install prerequisite packages
  debug:
    msg: '##### INSTALLING PREREQUISITE PACKAGES #####'

# Ensure the package manager cache is cleaned
- name: Clean all yum/dnf caches
  shell: 'dnf clean all'
  when: ansible_os_family == "RedHat"

# Ensure the fastest mirror is used for Rocky 8 and Rocky 9
- name: Use the fastest mirror on Rocky
  lineinfile:
    path: /etc/dnf/dnf.conf
    line: 'fastestmirror=1'
    insertafter: '^gpgcheck'
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version in ["8", "9"]

# Make sure the package manager cache is updated
- name: Refresh dnf cache on RedHat/Rocky
  dnf:
    update_cache: yes
  when: ansible_os_family == "RedHat"

# Ensure EPEL repository is installed for RedHat/Rocky
- name: Ensure EPEL repository for RedHat/Rocky
  dnf:
    name: epel-release
    state: latest
  when: ansible_os_family == "RedHat"

- name: install some necessary packages
  ansible.builtin.package:
    name: ['bash-completion', 'bc', 'ed', 'git', 'jq', 'mlocate', 'net-tools', 'sudo', 'unzip', 'python3-psycopg2', 'zip', 'tar', 'wget']
    state: latest
  when: ansible_os_family == "RedHat"

# Ensure pip is installed for Python 3.9
- name: Ensure pip is installed for Python 3.9
  dnf:
    name: python3-pip
    state: present
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "9"

# Find the path to pip3 for Rocky 9
- name: Find path to pip3
  command: "which pip3"
  register: pip_path

# Install psycopg2 via pip for Rocky 9 if not available via package manager
- name: Install psycopg2 via pip
  pip:
    name: psycopg2-binary
    state: latest
    executable: "{{ pip_path.stdout }}"
  when: ansible_os_family == "RedHat" and
        ansible_distribution_major_version == "9"

# Install OpenJDK and other Java packages
- name: Install Java (OpenJDK) and other packages for Rocky
  dnf:
    name: ['java-{{ java.version }}-openjdk-devel', 'tzdata-java', 'vim-enhanced']
    state: latest
  when: ansible_os_family == "RedHat"

# Install GraphicsMagick for thumbnail generation on Rocky
- name: Install GraphicsMagick for thumbnail generation
  dnf:
    name: GraphicsMagick
    state: latest
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution_major_version in ["8", "9"]
    - dataverse.thumbnails

# Ensure the Payara service account exists
- name: Payara service account must exist
  import_tasks: payara_service_account.yml

# Create directory for miscellaneous Dataverse files
- name: Create Dataverse misc files directory
  file:
    path: "{{ dataverse_misc_files_dir }}"
    state: directory
    owner: "{{ dataverse.payara.user }}"
    group: "{{ dataverse.payara.group }}"

- name: Install required system utilities
  package:
    name: procps
    state: present