---

- name: Install and configure Dataverse licenses
  debug:
    msg: '##### DATAVERSE LICENSES #####'

#### Requires community.postgresql from Ansible Galaxy
- name: Get API key for dataverseAdmin from the database
  community.postgresql.postgresql_query:
    db: "{{ db.postgres.name }}"
    login_user: "{{ db.postgres.user }}"
    login_password: "{{ db.postgres.pass }}"
    login_host: "{{ db.postgres.host }}"
    query: SELECT tokenstring FROM apitoken a JOIN authenticateduser u ON a.authenticateduser_id=u.id WHERE useridentifier='{{ dataverse.licenses.user }}' AND superuser
  changed_when: false
  register: token_result
  failed_when: token_result.rowcount != 1

- name: Calculate API token
  set_fact:
    api_token: '{{ token_result.query_result[0].tokenstring }}'

- name: Get existing licenses from Dataverse
  uri:
    url: "{{ dataverse.api.location }}/licenses"
    method: GET
    headers:
      X-Dataverse-key: '{{ api_token }}'
      Content-Type: 'application/json'
    status_code: 200
  register: current_licenses


# Filter desired licenses to add only if not already present
- name: Filter licenses to add
  set_fact:
    licenses_to_add: "{{ dataverse.licenses.licenses | rejectattr('name', 'in', current_licenses.json.data | map(attribute='name')) | list }}"

# Add licenses conditionally
- name: Configure available licenses
  uri:
    url: "{{ dataverse.api.location }}/licenses"
    method: POST
    headers:
      X-Dataverse-key: '{{ api_token }}'
    body: '{{ item }}'
    body_format: json
    status_code: 201,409
  register: license_update
  changed_when: license_update.status != 409
  loop: "{{ licenses_to_add }}"
  loop_control:
    label: "{{ item.name }}"
