---

- name: flush handlers to restart Payara if needed
  meta: flush_handlers

- name: build list from json
  ansible.builtin.set_fact:
    s3_bucketlist: "{{ localstack.buckets }}"

- name: debug list
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ s3_bucketlist }}"

- name: create buckets and set options
  block:
    - name: create bucket and set options
      ansible.builtin.include_tasks: localstack_create_bucket.yml
      vars:
        bucket_options: "{{ item }}"
      with_items: "{{ s3_bucketlist }}"
