---

- name: ensure payara service group exists
  ansible.builtin.group: 
    name: '{{ dataverse.payara.group }}' 
    state: present

- name: ensure payara service account exists
  ansible.builtin.user: 
    name: '{{ dataverse.payara.user }}' 
    group: '{{ dataverse.payara.group }}'
