---

- name: set postgresql init command
  set_fact:
    postgres_init: 'creates={{ postgres_config_dir }}/postgresql.conf /usr/pgsql-{{ dataverse_pg_version_short }}/bin/postgresql{{ dataverse_pg_version_short }}-setup initdb'
    when: db.use_rds == false

- name: init command needs a dash on postgres 10+
  set_fact:
    postgres_init: 'creates={{ postgres_config_dir }}/postgresql.conf /usr/pgsql-{{ dataverse_pg_version_short }}/bin/postgresql-{{ dataverse_pg_version_short }}-setup initdb'
  when:
   - dataverse_pg_version_short is search("1[0-9]")
   - db.use_rds == false

- name: have we init-ed postgres yet?
  stat:
    path: '/var/lib/pgsql/{{ db.postgres.version }}/initdb.log'
  register: postgres_initdb
  when:
   - db.use_rds == false

- name: init postgres
  shell: '{{ postgres_init }}'
  when:
   - db.use_rds == false
   - postgres_initdb.stat.exists == false
  notify: enable and restart postgres
