---

- name: import RPM-GPG-KEY-PGDG
  rpm_key:
    state: present
    key: https://download.postgresql.org/pub/repos/yum/keys/PGDG-RPM-GPG-KEY-RHEL

- name: install postgres repo RPM
  ansible.builtin.package:
    name: 'https://download.postgresql.org/pub/repos/yum/reporpms/EL-{{ ansible_distribution_major_version }}-x86_64/pgdg-redhat-repo-latest.noarch.rpm'
    state: present

- name: "RHEL/Rocky: disable PostgreSQL proper in the OS"
  shell: 'dnf -qy module disable postgresql'

- name: get postgres config directory
  set_fact:
    postgres_config_dir: '/var/lib/pgsql/{{ db.postgres.version }}/data'

- name: install postgres server on RedHat / Rocky
  ansible.builtin.package:
   name: 'postgresql{{ dataverse_pg_version_short }}-server'
   state: latest
  when: db.use_rds == false

- name: install postgres client on RedHat / Rocky for RDS
  ansible.builtin.package:
    name: 'postgresql{{ dataverse_pg_version_short }}'
    state: latest
  when: db.use_rds == true
