{
 "title": "overall metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "collectd_load_longterm", "legendFormat": "long term" },
    { "expr": "collectd_load_midterm", "legendFormat": "mid term" },
    { "expr": "collectd_load_shortterm", "legendFormat": "short term" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "collectd_memory", "legendFormat": "{{memory}}" }
   ]
  },
  {
   "title": "Glassfish - overall heap usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "collectd_GenericJMX_memory{type =~ \"^heap.*$\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}